<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Atlit_model extends CI_Model
{

    public $table = 'atlit';
    public $id = 'id_atlit';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_atlit', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('namadepan', $q);
	$this->db->or_like('namabelakang', $q);
	$this->db->or_like('panggilan', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('primaryposision', $q);
	$this->db->or_like('secondaryposision', $q);
	$this->db->or_like('negara', $q);
	$this->db->or_like('provinsi', $q);
	$this->db->or_like('kabkota', $q);
	$this->db->or_like('club', $q);
	$this->db->or_like('profesi', $q);
	$this->db->or_like('alamat_provinsi', $q);
	$this->db->or_like('alamat_kabkota', $q);
	$this->db->or_like('alamat_kecamatan', $q);
	$this->db->or_like('alamat_desa', $q);
	$this->db->or_like('kodepos', $q);
	$this->db->or_like('rangking_nasional', $q);
	$this->db->or_like('rangking_provinsi', $q);
	$this->db->or_like('warna_sabuk', $q);
	$this->db->or_like('tinggi', $q);
	$this->db->or_like('berat', $q);
	$this->db->or_like('golongan_darah', $q);
	$this->db->or_like('foto', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_atlit', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('namadepan', $q);
	$this->db->or_like('namabelakang', $q);
	$this->db->or_like('panggilan', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('primaryposision', $q);
	$this->db->or_like('secondaryposision', $q);
	$this->db->or_like('negara', $q);
	$this->db->or_like('provinsi', $q);
	$this->db->or_like('kabkota', $q);
	$this->db->or_like('club', $q);
	$this->db->or_like('profesi', $q);
	$this->db->or_like('alamat_provinsi', $q);
	$this->db->or_like('alamat_kabkota', $q);
	$this->db->or_like('alamat_kecamatan', $q);
	$this->db->or_like('alamat_desa', $q);
	$this->db->or_like('kodepos', $q);
	$this->db->or_like('rangking_nasional', $q);
	$this->db->or_like('rangking_provinsi', $q);
	$this->db->or_like('warna_sabuk', $q);
	$this->db->or_like('tinggi', $q);
	$this->db->or_like('berat', $q);
	$this->db->or_like('golongan_darah', $q);
	$this->db->or_like('foto', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Atlit_model.php */
/* Location: ./application/models/Atlit_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-15 11:32:27 */
/* http://harviacode.com */