<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Member_model extends CI_Model
{

    public $table = 'member';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('type_mobil', $q);
	$this->db->or_like('kode_mesin', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('no_rangka', $q);
	$this->db->or_like('no_mesin', $q);
	$this->db->or_like('plat_nomor', $q);
	$this->db->or_like('warna', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('pekerjaan', $q);
	$this->db->or_like('hp', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('medsos', $q);
	$this->db->or_like('foto_member', $q);
	$this->db->or_like('foto_unit', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('type_mobil', $q);
	$this->db->or_like('kode_mesin', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('no_rangka', $q);
	$this->db->or_like('no_mesin', $q);
	$this->db->or_like('plat_nomor', $q);
	$this->db->or_like('warna', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('pekerjaan', $q);
	$this->db->or_like('hp', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('medsos', $q);
	$this->db->or_like('foto_member', $q);
	$this->db->or_like('foto_unit', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Member_model.php */
/* Location: ./application/models/Member_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-09 15:48:32 */
/* http://harviacode.com */